#!/bin/bash

echo "🔍 DIAGNÓSTICO COMPLETO DEL SISTEMA DUAL"
echo "========================================"
echo ""

echo "📊 1. Verificando Backend en Railway..."
echo "----------------------------------------"

echo "Health check:"
curl -s "https://api.kdsapp.site/health" | jq . 2>/dev/null || curl -s "https://api.kdsapp.site/health"
echo ""

echo "Webhook principal:"
curl -s "https://api.kdsapp.site/webhook/whatsapp?hub.mode=subscribe&hub.verify_token=kds_webhook_token_2026&hub.challenge=TEST123"
echo ""

echo "Webhook legacy:"
curl -s "https://api.kdsapp.site/webhook/whatsapp-legacy?hub.mode=subscribe&hub.verify_token=kds_webhook_token_2026&hub.challenge=TEST123"
echo ""

echo ""
echo "📱 2. Verificando Frontend en Firebase..."
echo "----------------------------------------"

echo "Verificando facebook-config-legacy.js:"
curl -s "https://kdsapp.site/facebook-config-legacy.js" | grep -A 3 "callbackUrl:"
echo ""

echo "Verificando onboarding-2.html existe:"
curl -s -o /dev/null -w "Status: %{http_code}\n" "https://kdsapp.site/onboarding-2.html"
echo ""

echo ""
echo "🔧 3. URLs que deben estar en Meta Dashboard (App Legacy: 1860852208127086)"
echo "----------------------------------------"
echo ""
echo "Facebook Login > Settings > Valid OAuth Redirect URIs:"
echo "  ✅ https://api.kdsapp.site/api/whatsapp/callback-legacy"
echo ""
echo "WhatsApp > Configuration > Embedded Signup Callback URL:"
echo "  ✅ https://api.kdsapp.site/api/whatsapp/callback-legacy"
echo ""
echo "WhatsApp > Configuration > Webhook URL:"
echo "  ✅ https://api.kdsapp.site/webhook/whatsapp-legacy"
echo ""
echo "WhatsApp > Configuration > Verify Token:"
echo "  ✅ kds_webhook_token_2026"
echo ""

echo ""
echo "🎯 4. URLs para verificar manualmente en Meta:"
echo "----------------------------------------"
echo "App Settings: https://developers.facebook.com/apps/1860852208127086/settings/basic/"
echo "Facebook Login: https://developers.facebook.com/apps/1860852208127086/fb-login/settings/"
echo "WhatsApp Config: https://developers.facebook.com/apps/1860852208127086/whatsapp-business/wa-settings/"
echo ""

echo ""
echo "📝 5. Checklist de Verificación:"
echo "----------------------------------------"
echo "[ ] El app está en modo 'Live' (no Development)"
echo "[ ] OAuth Redirect URI configurada en Facebook Login"
echo "[ ] Embedded Signup Callback configurada en WhatsApp"
echo "[ ] Webhook URL configurada y verificada"
echo "[ ] App Domains incluye: kdsapp.site y api.kdsapp.site"
echo "[ ] El portfolio 1473689432774278 está activo"
echo "[ ] WhatsApp Business Account 417281831476993 está activo"
echo ""

echo "✅ Diagnóstico completo"
