#!/bin/bash

# Script de verificación del progreso de onboarding
# Este script te ayuda a verificar que el progreso se está leyendo correctamente

echo "================================================"
echo "🔍 VERIFICACIÓN DE PROGRESO DE ONBOARDING"
echo "================================================"
echo ""

# Configuración
TENANT_ID="${1:-tu-tenant-id}"

if [ "$TENANT_ID" = "tu-tenant-id" ]; then
  echo "❌ Error: Debes proporcionar tu TENANT_ID"
  echo ""
  echo "Uso:"
  echo "  ./verificar-progreso.sh <TENANT_ID>"
  echo ""
  echo "Ejemplo:"
  echo "  ./verificar-progreso.sh abc123"
  echo ""
  exit 1
fi

echo "📋 Configuración:"
echo "   Tenant ID: $TENANT_ID"
echo ""

echo "================================================"
echo "PASO 1: Verificar el progreso guardado en Firebase"
echo "================================================"
echo ""
echo "Abre la siguiente URL en tu navegador:"
echo ""
echo "https://console.firebase.google.com/project/kds-app-7f1d3/database/kds-app-7f1d3-default-rtdb/data/~2Ftenants~2F${TENANT_ID}~2Fonboarding"
echo ""
echo "Verifica que exista el campo 'progress' con un valor numérico (ej: 75)"
echo ""
read -p "Presiona Enter cuando hayas verificado..."
echo ""

echo "================================================"
echo "PASO 2: Abrir el dashboard con la consola del navegador"
echo "================================================"
echo ""
echo "1. Abre esta URL:"
echo "   https://kdsapp.site/dashboard.html?tenant=${TENANT_ID}"
echo ""
echo "2. Abre la consola del navegador (F12 → Consola)"
echo ""
echo "3. Busca estos logs:"
echo ""
echo "   ✅ Si el progreso se lee correctamente desde Firebase:"
echo "      📊 Progreso de onboarding leído desde Firebase: XX%"
echo ""
echo "   ⚠️  Si no existe en Firebase y se calcula:"
echo "      📊 Progreso de onboarding calculado (no existía en Firebase): XX%"
echo ""
echo "   📊 Estado inicial del bot:"
echo "      🤖 Estado inicial del bot: ON/OFF (progreso: XX%)"
echo ""
echo "   🎨 UI del bot:"
echo "      🎨 Actualizando UI del bot:"
echo "        - Estado del bot: ON/OFF"
echo "        - Progreso de onboarding: XX%"
echo "        - Puede activar (>= 75%): true/false"
echo ""
read -p "Presiona Enter cuando hayas abierto la consola..."
echo ""

echo "================================================"
echo "PASO 3: Intentar activar el bot"
echo "================================================"
echo ""
echo "1. Haz clic en el toggle del bot (si no está deshabilitado)"
echo ""
echo "2. Verifica estos logs en la consola:"
echo ""
echo "   🎯 Toggle bot llamado:"
echo "      - Estado actual del bot: OFF"
echo "      - Progreso local (onboardingPercentage): XX%"
echo "      - Puede activar (>= 75%): true/false"
echo "      - Estado de onboarding: {...}"
echo ""
echo "   🔍 Validación en Firebase:"
echo "      - Progreso guardado en Firebase: XX%"
echo "      - Steps en Firebase: {...}"
echo "      - Completed en Firebase: true/false"
echo ""
echo "   ✅ Si se activa correctamente:"
echo "      ✅ Estado del bot actualizado en Firebase: ACTIVO (true)"
echo ""
echo "   🚫 Si el progreso es < 75%:"
echo "      🚫 Validación de progreso falló."
echo "         - Progreso en Firebase: XX%"
echo "         - Progreso local: XX%"
echo ""
read -p "Presiona Enter cuando hayas probado el toggle..."
echo ""

echo "================================================"
echo "PASO 4: Verificar discrepancias"
echo "================================================"
echo ""
echo "Si el progreso local es diferente al de Firebase, se mostrará:"
echo ""
echo "   ⚠️ Discrepancia detectada entre progreso local (XX%) y Firebase (YY%). Sincronizando..."
echo ""
echo "Esto es NORMAL y el sistema se sincronizará automáticamente."
echo ""
read -p "Presiona Enter para continuar..."
echo ""

echo "================================================"
echo "PASO 5: Verificar alertas en la UI"
echo "================================================"
echo ""
echo "1. Si el progreso es < 75% y intentas activar el bot:"
echo "   → Verás una alerta: '⚠️ Para activar el bot, debes completar al menos el 75%'"
echo ""
echo "2. Si hay discrepancia entre local y Firebase:"
echo "   → Verás una alerta con el progreso del servidor"
echo ""
echo "3. Si el progreso es >= 75%:"
echo "   → El toggle debe estar habilitado y funcionando"
echo "   → La advertencia no debe mostrarse"
echo ""
read -p "Presiona Enter para ver el resumen..."
echo ""

echo "================================================"
echo "📊 RESUMEN DE VERIFICACIÓN"
echo "================================================"
echo ""
echo "✅ Checklist:"
echo ""
echo "   [ ] El progreso se lee desde Firebase al cargar el dashboard"
echo "   [ ] Los logs muestran el progreso correcto (no 0%)"
echo "   [ ] El toggle se habilita si progreso >= 75%"
echo "   [ ] El toggle se deshabilita si progreso < 75%"
echo "   [ ] La validación en Firebase funciona al activar el bot"
echo "   [ ] Las alertas se muestran correctamente"
echo "   [ ] No hay errores en la consola del navegador"
echo ""
echo "================================================"
echo ""
echo "Si alguno de estos checks falla, copia los logs de la consola"
echo "y compártelos para investigar el problema."
echo ""
echo "Logs importantes:"
echo "   - 📊 Progreso de onboarding leído desde Firebase: XX%"
echo "   - 🤖 Estado inicial del bot: ON/OFF (progreso: XX%)"
echo "   - 🎯 Toggle bot llamado: {...}"
echo "   - 🔍 Validación en Firebase: {...}"
echo ""
echo "================================================"
echo "✅ Verificación completada"
echo "================================================"
